import type { Metadata } from 'next';
import '@frontend/styles/global.scss';
import SkipLink from '@frontend/components/SkipLink';
import styles from './layout.module.scss';
import Header from '@frontend/components/Header';
import Footer from '@frontend/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SkipLink />
        <div className={styles.layoutContainer}>
          <Header />
          <main id="main" className={styles.main}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
